//#line 2 "/opt/ros/indigo/share/dynamic_reconfigure/templates/ConfigType.h.template"
// *********************************************************
// 
// File autogenerated for the kobuki_safety_controller package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

#ifndef __kobuki_safety_controller__REACTIONCONFIG_H__
#define __kobuki_safety_controller__REACTIONCONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace kobuki_safety_controller
{
  class ReactionConfigStatics;
  
  class ReactionConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(ReactionConfig &config, const ReactionConfig &max, const ReactionConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const ReactionConfig &config1, const ReactionConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, ReactionConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const ReactionConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, ReactionConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const ReactionConfig &config) const = 0;
      virtual void getValue(const ReactionConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level, 
          std::string a_description, std::string a_edit_method, T ReactionConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T (ReactionConfig::* field);

      virtual void clamp(ReactionConfig &config, const ReactionConfig &max, const ReactionConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const ReactionConfig &config1, const ReactionConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, ReactionConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const ReactionConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, ReactionConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const ReactionConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const ReactionConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, ReactionConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    template<class T, class PT>
    class GroupDescription : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, ReactionConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<ReactionConfig::AbstractGroupDescriptionConstPtr> groups;
    };
    
class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(ReactionConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("time_to_extend_bump_cliff_events"==(*_i)->name){time_to_extend_bump_cliff_events = boost::any_cast<double>(val);}
        if("time_to_seperate_bump_cliff_events"==(*_i)->name){time_to_seperate_bump_cliff_events = boost::any_cast<double>(val);}
        if("bumper_forward_velocity"==(*_i)->name){bumper_forward_velocity = boost::any_cast<double>(val);}
        if("bumper_rotated_velocity"==(*_i)->name){bumper_rotated_velocity = boost::any_cast<double>(val);}
      }
    }

    double time_to_extend_bump_cliff_events;
double time_to_seperate_bump_cliff_events;
double bumper_forward_velocity;
double bumper_rotated_velocity;

    bool state;
    std::string name;

    class VEL_AMPLIFIER
{
  public:
    VEL_AMPLIFIER()
    {
      state = true;
      name = "vel_amplifier";
    }

    void setParams(ReactionConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("amplifier_center"==(*_i)->name){amplifier_center = boost::any_cast<double>(val);}
        if("amplifier_right"==(*_i)->name){amplifier_right = boost::any_cast<double>(val);}
        if("amplifier_left"==(*_i)->name){amplifier_left = boost::any_cast<double>(val);}
      }
    }

    double amplifier_center;
double amplifier_right;
double amplifier_left;

    bool state;
    std::string name;

    
}vel_amplifier;

}groups;



//#line 273 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double time_to_extend_bump_cliff_events;
//#line 273 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double time_to_seperate_bump_cliff_events;
//#line 273 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double bumper_forward_velocity;
//#line 273 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double bumper_rotated_velocity;
//#line 17 "/home/tongsky/Documents/kobuki_ws/src/kobuki_safety_controller/cfg/Reaction.cfg"
      double amplifier_center;
//#line 20 "/home/tongsky/Documents/kobuki_ws/src/kobuki_safety_controller/cfg/Reaction.cfg"
      double amplifier_right;
//#line 23 "/home/tongsky/Documents/kobuki_ws/src/kobuki_safety_controller/cfg/Reaction.cfg"
      double amplifier_left;
//#line 218 "/opt/ros/indigo/share/dynamic_reconfigure/templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("ReactionConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const ReactionConfig &__max__ = __getMax__();
      const ReactionConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const ReactionConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const ReactionConfig &__getDefault__();
    static const ReactionConfig &__getMax__();
    static const ReactionConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();
    
  private:
    static const ReactionConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void ReactionConfig::ParamDescription<std::string>::clamp(ReactionConfig &config, const ReactionConfig &max, const ReactionConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class ReactionConfigStatics
  {
    friend class ReactionConfig;
    
    ReactionConfigStatics()
    {
ReactionConfig::GroupDescription<ReactionConfig::DEFAULT, ReactionConfig> Default("Default", "", 0, 0, true, &ReactionConfig::groups);
//#line 273 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.time_to_extend_bump_cliff_events = 0.0;
//#line 273 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.time_to_extend_bump_cliff_events = std::numeric_limits<double>::infinity();
//#line 273 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.time_to_extend_bump_cliff_events = 2.0;
//#line 273 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(ReactionConfig::AbstractParamDescriptionConstPtr(new ReactionConfig::ParamDescription<double>("time_to_extend_bump_cliff_events", "double", 0, "total time to react safety sensors", "", &ReactionConfig::time_to_extend_bump_cliff_events)));
//#line 273 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(ReactionConfig::AbstractParamDescriptionConstPtr(new ReactionConfig::ParamDescription<double>("time_to_extend_bump_cliff_events", "double", 0, "total time to react safety sensors", "", &ReactionConfig::time_to_extend_bump_cliff_events)));
//#line 273 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.time_to_seperate_bump_cliff_events = 0.0;
//#line 273 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.time_to_seperate_bump_cliff_events = std::numeric_limits<double>::infinity();
//#line 273 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.time_to_seperate_bump_cliff_events = 1.0;
//#line 273 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(ReactionConfig::AbstractParamDescriptionConstPtr(new ReactionConfig::ParamDescription<double>("time_to_seperate_bump_cliff_events", "double", 0, "first interval time to react safety sensors backward behavior", "", &ReactionConfig::time_to_seperate_bump_cliff_events)));
//#line 273 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(ReactionConfig::AbstractParamDescriptionConstPtr(new ReactionConfig::ParamDescription<double>("time_to_seperate_bump_cliff_events", "double", 0, "first interval time to react safety sensors backward behavior", "", &ReactionConfig::time_to_seperate_bump_cliff_events)));
//#line 273 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.bumper_forward_velocity = -std::numeric_limits<double>::infinity();
//#line 273 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.bumper_forward_velocity = std::numeric_limits<double>::infinity();
//#line 273 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.bumper_forward_velocity = 0.08;
//#line 273 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(ReactionConfig::AbstractParamDescriptionConstPtr(new ReactionConfig::ParamDescription<double>("bumper_forward_velocity", "double", 0, "backward velocity [m/s], (already set negative sign in source code)", "", &ReactionConfig::bumper_forward_velocity)));
//#line 273 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(ReactionConfig::AbstractParamDescriptionConstPtr(new ReactionConfig::ParamDescription<double>("bumper_forward_velocity", "double", 0, "backward velocity [m/s], (already set negative sign in source code)", "", &ReactionConfig::bumper_forward_velocity)));
//#line 273 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.bumper_rotated_velocity = -6.28318530718;
//#line 273 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.bumper_rotated_velocity = 6.28318530718;
//#line 273 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.bumper_rotated_velocity = 0.5;
//#line 273 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(ReactionConfig::AbstractParamDescriptionConstPtr(new ReactionConfig::ParamDescription<double>("bumper_rotated_velocity", "double", 0, "rotation velocity [rad/s]", "", &ReactionConfig::bumper_rotated_velocity)));
//#line 273 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(ReactionConfig::AbstractParamDescriptionConstPtr(new ReactionConfig::ParamDescription<double>("bumper_rotated_velocity", "double", 0, "rotation velocity [rad/s]", "", &ReactionConfig::bumper_rotated_velocity)));
ReactionConfig::GroupDescription<ReactionConfig::DEFAULT::VEL_AMPLIFIER, ReactionConfig::DEFAULT> vel_amplifier("vel_amplifier", "", 0, 1, true, &ReactionConfig::DEFAULT::vel_amplifier);
//#line 17 "/home/tongsky/Documents/kobuki_ws/src/kobuki_safety_controller/cfg/Reaction.cfg"
      __min__.amplifier_center = -std::numeric_limits<double>::infinity();
//#line 17 "/home/tongsky/Documents/kobuki_ws/src/kobuki_safety_controller/cfg/Reaction.cfg"
      __max__.amplifier_center = std::numeric_limits<double>::infinity();
//#line 17 "/home/tongsky/Documents/kobuki_ws/src/kobuki_safety_controller/cfg/Reaction.cfg"
      __default__.amplifier_center = 1.0;
//#line 17 "/home/tongsky/Documents/kobuki_ws/src/kobuki_safety_controller/cfg/Reaction.cfg"
      vel_amplifier.abstract_parameters.push_back(ReactionConfig::AbstractParamDescriptionConstPtr(new ReactionConfig::ParamDescription<double>("amplifier_center", "double", 0, "The amplifier of center reactive velocity", "", &ReactionConfig::amplifier_center)));
//#line 17 "/home/tongsky/Documents/kobuki_ws/src/kobuki_safety_controller/cfg/Reaction.cfg"
      __param_descriptions__.push_back(ReactionConfig::AbstractParamDescriptionConstPtr(new ReactionConfig::ParamDescription<double>("amplifier_center", "double", 0, "The amplifier of center reactive velocity", "", &ReactionConfig::amplifier_center)));
//#line 20 "/home/tongsky/Documents/kobuki_ws/src/kobuki_safety_controller/cfg/Reaction.cfg"
      __min__.amplifier_right = -std::numeric_limits<double>::infinity();
//#line 20 "/home/tongsky/Documents/kobuki_ws/src/kobuki_safety_controller/cfg/Reaction.cfg"
      __max__.amplifier_right = std::numeric_limits<double>::infinity();
//#line 20 "/home/tongsky/Documents/kobuki_ws/src/kobuki_safety_controller/cfg/Reaction.cfg"
      __default__.amplifier_right = 1.0;
//#line 20 "/home/tongsky/Documents/kobuki_ws/src/kobuki_safety_controller/cfg/Reaction.cfg"
      vel_amplifier.abstract_parameters.push_back(ReactionConfig::AbstractParamDescriptionConstPtr(new ReactionConfig::ParamDescription<double>("amplifier_right", "double", 0, "The amplifier of right reactive velocity", "", &ReactionConfig::amplifier_right)));
//#line 20 "/home/tongsky/Documents/kobuki_ws/src/kobuki_safety_controller/cfg/Reaction.cfg"
      __param_descriptions__.push_back(ReactionConfig::AbstractParamDescriptionConstPtr(new ReactionConfig::ParamDescription<double>("amplifier_right", "double", 0, "The amplifier of right reactive velocity", "", &ReactionConfig::amplifier_right)));
//#line 23 "/home/tongsky/Documents/kobuki_ws/src/kobuki_safety_controller/cfg/Reaction.cfg"
      __min__.amplifier_left = -std::numeric_limits<double>::infinity();
//#line 23 "/home/tongsky/Documents/kobuki_ws/src/kobuki_safety_controller/cfg/Reaction.cfg"
      __max__.amplifier_left = std::numeric_limits<double>::infinity();
//#line 23 "/home/tongsky/Documents/kobuki_ws/src/kobuki_safety_controller/cfg/Reaction.cfg"
      __default__.amplifier_left = 0.6;
//#line 23 "/home/tongsky/Documents/kobuki_ws/src/kobuki_safety_controller/cfg/Reaction.cfg"
      vel_amplifier.abstract_parameters.push_back(ReactionConfig::AbstractParamDescriptionConstPtr(new ReactionConfig::ParamDescription<double>("amplifier_left", "double", 0, "The amplifier of left reactive velocity", "", &ReactionConfig::amplifier_left)));
//#line 23 "/home/tongsky/Documents/kobuki_ws/src/kobuki_safety_controller/cfg/Reaction.cfg"
      __param_descriptions__.push_back(ReactionConfig::AbstractParamDescriptionConstPtr(new ReactionConfig::ParamDescription<double>("amplifier_left", "double", 0, "The amplifier of left reactive velocity", "", &ReactionConfig::amplifier_left)));
//#line 121 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      vel_amplifier.convertParams();
//#line 121 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.groups.push_back(ReactionConfig::AbstractGroupDescriptionConstPtr(new ReactionConfig::GroupDescription<ReactionConfig::DEFAULT::VEL_AMPLIFIER, ReactionConfig::DEFAULT>(vel_amplifier)));
//#line 121 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __group_descriptions__.push_back(ReactionConfig::AbstractGroupDescriptionConstPtr(new ReactionConfig::GroupDescription<ReactionConfig::DEFAULT::VEL_AMPLIFIER, ReactionConfig::DEFAULT>(vel_amplifier)));
//#line 245 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.convertParams();
//#line 245 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __group_descriptions__.push_back(ReactionConfig::AbstractGroupDescriptionConstPtr(new ReactionConfig::GroupDescription<ReactionConfig::DEFAULT, ReactionConfig>(Default)));
//#line 356 "/opt/ros/indigo/share/dynamic_reconfigure/templates/ConfigType.h.template"

      for (std::vector<ReactionConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__); 
    }
    std::vector<ReactionConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<ReactionConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    ReactionConfig __max__;
    ReactionConfig __min__;
    ReactionConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const ReactionConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static ReactionConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &ReactionConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const ReactionConfig &ReactionConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const ReactionConfig &ReactionConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const ReactionConfig &ReactionConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<ReactionConfig::AbstractParamDescriptionConstPtr> &ReactionConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<ReactionConfig::AbstractGroupDescriptionConstPtr> &ReactionConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const ReactionConfigStatics *ReactionConfig::__get_statics__()
  {
    const static ReactionConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = ReactionConfigStatics::get_instance();
    
    return statics;
  }


}

#endif // __REACTIONRECONFIGURATOR_H__
